spring.application.name=TPApiGateway
server.port=8765
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.instance.prefer-ip-address=true

jwt.public_key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvhBaYV0kitTo3N6r9C5fivxSx4iGfiI3w3ZTsDVDjW4e8MiBJscsjSKXqQFn8pmTsb+LvPCo3SjHen8aA82lHkEOHDOW0hLhvX5XOzglcCljkSXV9PMT3+P3N/JBl8RXzcUEfs1bjJGSuBiORgD7e0uSsOOO7oJuBfwlC2eVtgJMD7xf/x8HEw+nGrK5QBaB6WL98GmYUgOGbdyVgha5Qa9YCVt+SlWP4AlgmzpiTIKxzaG6uoz6Zj6c4l2AFR7in71cvNpeZzG5W2ftI1WmBkAAf6o3mHN9qZtweVVBDJJnJl7x0M/VmuWG63adigVtbPs/dQJ4Wnamc9tKc1GhDQIDAQAB
